version: '3.7'

services:
  mongodb-Cont:
    image: mongo:latest
    container_name: mongodb-Cont
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_cont:/data/db

  server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb-Cont
    volumes:
      - ./src:/usr/app/src
      - ./node_modules:/usr/app/node_modules

volumes:
  mongodb_data_cont:

    